### ISSUE TITLE
Problem replacing filled area with transparent color

### ISSUE THREAD

**Issue by pnykamp** [Chintan-Dave/UIImageScanlineFloodfill#13]
First, let me say very nice piece of code, thank you. 

I've been trying to replace the fill color with a transparent color. I've tried setting newcolor to:

```
imageView.newcolor = [UIColor clearColor];
imageView.newcolor = [UIColor colorWithWhite:0.0 alpha:0.0];
imageView.newcolor = [UIColor colorWithWhite:1.0 alpha:0.0];
```

but the filled color ends up being either black or white.

Can you point me in the right direction?

Thanks.

**Comment by sushilmca87** [comment]
after passing last argument still its not working
