### ISSUE TITLE
CGContextDrawImage bad access crash

### ISSUE THREAD

**Issue by BenBarahona** [Chintan-Dave/UIImageScanlineFloodfill#15]
While using and testing this library, I noticed it was crashing on UIImage+Floodfill.m, at about line 60, where you call 
CGContextDrawImage(context, CGRectMake(0, 0, width, height), imageRef);

While I am not 100% sure of the causes, I tested with both JPG and PNG and multiple image sources (device camera pictures, device screenshots pictures, etc) and found that it crashed on some png images, specifically those that were screenshots of the device.  So then digging a bit further about the bad access, I thought it might have something to do with the imageRef.

So I tested it out, at about line 40 you do: 
CGImageRef imageRef = [self CGImage];

so instead of obtaining the CGImageRef that way, I used the image's NSData:

CGDataProviderRef imgDataProvider = CGDataProviderCreateWithCFData((CFDataRef)UIImagePNGRepresentation(self));

CGImageRef imageRef = CGImageCreateWithPNGDataProvider(imgDataProvider, NULL, true, kCGRenderingIntentDefault);

I made it a PNG because I was using the library to make an alpha flood-fill, instead of a solid color one.  As long as the CGDataRef and CGImageRef are obtained from the same format, it fixed the bad access crash.  Also, I did not include the release of memory that holds those objects as I do it later in the code, but just wanted to point it out.

**Comment by Chintan-Dave** [comment]
hi thanks to put your effort in this work. Can you give me that image so I can test and solve this issue.

**Comment by TTMarshelDaniel** [comment]
Thanks.

**Comment by BenBarahona** [comment]
@Chintan-Dave Sorry for the late response, here are 3 pictures (all screenshots from my iphone 5)  which consistently cause the crash.  With the changes I made, the crashes stopped.
![img_9121](https://cloud.githubusercontent.com/assets/1316800/8967727/fbd6ad36-35f5-11e5-9cc9-8d11bd349d48.JPG)
![img_9126](https://cloud.githubusercontent.com/assets/1316800/8967728/fbd7829c-35f5-11e5-9930-bb9ef7f398ea.PNG)
![img_9125](https://cloud.githubusercontent.com/assets/1316800/8967742/1bcb3300-35f6-11e5-9500-e10844ad6995.PNG)

**Comment by ar9jun** [comment]
Thank you so much! I was struggling with this one.

**Comment by marta-rodriguez** [comment]
Thank you very much @BenBarahona, I was stuck in this error and your solution works!!

**Comment by Chintan-Dave** [comment]
@BenBarahona thanks to providing the workaround for this issue. 

I have tested this issue with given images and it seems like it is solved now with #23 & #27. 

Closing this for now but if anyone found it again please feel free to reopen it.
