### ISSUE TITLE
Strange behavior

### ISSUE THREAD

**Issue by rickardz** [Chintan-Dave/UIImageScanlineFloodfill#2]
Hey man, great job putting this together! Found a strange issue though, when i fill the background when I have this circle in my image it doesn't fill the whole area:
![skarmavbild 2013-10-19 kl 16 37 37](https://f.cloud.github.com/assets/5416149/1366339/17614b7a-38cc-11e3-9adc-bd0e2227594e.png)

But when I draw a circle a little bit higher it behaves correct. Any ideas why?
![skarmavbild 2013-10-19 kl 16 41 43](https://f.cloud.github.com/assets/5416149/1366355/9d4329de-38cc-11e3-865c-4856545bd6df.png)

**Comment by Chintan-Dave** [comment]
Solved!
