### ISSUE TITLE
More options to be perfect

### ISSUE THREAD

**Issue by prsolucoes** [Chintan-Dave/UIImageScanlineFloodfill#22]
- I think that can have a border detection or tolerance by color

**Comment by Chintan-Dave** [comment]
This one statement is not enough to understand. Explain more in detail.

**Comment by prsolucoes** [comment]
Instead of only default tolerance, you can make an option to exclude colors that can accept fill.
Example:
When i touch the image, only the colors [white, red, gree, yellow, blue] is acceptable to be filled.

**Comment by Chintan-Dave** [comment]
Can you give me any link of working tool as u explain so that I can understand what you want to say. Any app or any online image tool or any mac app.

**Comment by Chintan-Dave** [comment]
I am closing this because of unclear statement. Let me know if you have proper example. I will reopen it.

**Comment by prsolucoes** [comment]
As i said, today when you touch the image border the library paint it. If we can ignore some colors, we can make the border black and ignore it, so the children only will be able to touch the areas without that color. Understand?

**Comment by Chintan-Dave** [comment]
I think I understood. But this kind of list is very long. Ignore color, Ignore color range, Ignore some area, Ignore double touch etc.. If we twist this list become unlimited like mix original color and new color instead of replacing, insted of ignoring some color just work on some color etc...

**Comment by prsolucoes** [comment]
I think that ignore a list of colors with will sufficient.

```objective-c
@[
[UIColor blackColor],
[UIColor redColor],
[UIColor greenColor]
]
```

Thanks.

**Comment by Chintan-Dave** [comment]
I am not talking about list of colors but list of this kind of feature. This kind of feature is not suitable in Basic flood fill algo. That is specific need of specific need.
