### ISSUE TITLE
EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by samane78** [Chintan-Dave/UIImageScanlineFloodfill#23]
In method (from UIImage+FloodFill.m)
- (UIImage *) floodFillFromPoint:(CGPoint)startPoint withColor:(UIColor *)newColor andTolerance:(int)tolerance useAntiAlias:(BOOL)antiAlias

Line 391, "if (y<height)" should be "if((y+1) < height) else you may see an EXC_BAD_ACCESS.

Also, shouldn't imageData be allocated like this ? 

NSUInteger bytesPerPixel = CGImageGetBitsPerPixel(imageRef) / 8;
unsigned char *imageData = malloc(height \* width \* bytesPerPixel);

**Comment by vietphu** [comment]
I also have EXC BAC ACCESS in this method, but in the following line:
        CGContextDrawImage(context, CGRectMake(0, 0, width, height), imageRef);

**Comment by Chintan-Dave** [comment]
@vietphu Check #15 . That might solve your issue.

**Comment by Chintan-Dave** [comment]
@samane78  I have applied your suggestion for imageData.
