### ISSUE TITLE
whats wrong? unsupported parameter combination: 8 integer bits/component; 24 bits/pixel; 3-component color space; kCGImageAlphaNone; 2480 bytes/row.

### ISSUE THREAD

**Issue by whatya** [Chintan-Dave/UIImageScanlineFloodfill#25]
Sep 15 22:42:46 whatya UIImage Scanline Floodfill[1507] <Error>: CGBitmapContextCreate: unsupported parameter combination: 8 integer bits/component; 24 bits/pixel; 3-component color space; kCGImageAlphaNone; 2480 bytes/row.
Sep 15 22:42:46 whatya UIImage Scanline Floodfill[1507] <Error>: CGContextDrawImage: invalid context 0x0. This is a serious error. This application, or a library it uses, is using an invalid context  and is thereby contributing to an overall degradation of system stability and reliability. This notice is a courtesy: please fix this problem. It will become a fatal error in an upcoming update.

**Comment by Chintan-Dave** [comment]
@whatya  I tried but not able to get this kind of logs. Maybe this is solved. Reopen this with some more information if you are still getting logs.

**Comment by DevendraKadam** [comment]
issue is because of image is 24 bit per pixel it should be always 32 bpp can you tell me y it should be always 32 @Chintan-Dave
