### ISSUE TITLE
How to prevent coloring over the outlines on image?

### ISSUE THREAD

**Issue by msinv** [Chintan-Dave/UIImageScanlineFloodfill#26]
With flood fill, how can we prevent user from preventing coloring over the outlines? It will be helpful if you can post code snippet to do it. Are there any specific requirements for the image formatting? Should they be in png / jpg format or something else?

**Comment by bismasaeed00** [comment]
Try changing the value of tolerance. 0 tolerance never color outline but not fill image properly and 100 tolerance fill image properly but color the outline sometimes. Try to adjust the value.
