### ISSUE TITLE
Flood Fill With Gradient

### ISSUE THREAD

**Issue by Asif-Rahman-Nestedapps** [Chintan-Dave/UIImageScanlineFloodfill#32]
Could you please tell me how to apply gradient in the flood fill algorithm you provided.Everything works fine with solid colors and i thank you for that. I tried to apply gradient color using UIcolor colorwithpattern image , but it's not working,showing weird colors. If you could help me that, that'd be of great help thank you. For you consideration here's a code snippet:

           filledImage= [_imageView.image floodFillFromPoint:CGPointMake((touchPoint.x*ScaleFactor)/_zoomScrollview.zoomScale,( touchPoint.y*ScaleFactor)/_zoomScrollview.zoomScale) withColor:[UIColor colorWithPatternImage:[UIImage imageNamed:@"G2.png"]] andTolerance:5.0 ];

**Comment by dmaulikr** [comment]
@Asif-Rahman-Nestedapps have you got any solution?

**Comment by Chintan-Dave** [comment]
@Asif-Rahman-Nestedapps  Till now no plan to implement that. I will inform here if we make a plan for that. If you have any solution and ready to contribute we can move its priority higher.
