### ISSUE TITLE
Flood Fill with clear color

### ISSUE THREAD

**Issue by chetanpanchal94** [Chintan-Dave/UIImageScanlineFloodfill#34]
I am trying to fill area with clear color but it is filling it with black color.

**Comment by Chintan-Dave** [comment]
This project still not support transparent colour properly.

If you want to contribute here is a separate branch for that: https://github.com/Chintan-Dave/UIImageScanlineFloodfill/tree/Implement-Alpha/UIImage%20Scanline%20Floodfill/UIImage%20Scanline%20Floodfill

**Comment by yo1995** [comment]
will there be any update on this issue?
many present libraries do not correctly support transparency, whereas commercial softwares like PS or so do have correct support for that.

Could you provide any information about how to improve it?

To my experience it should be related with palette image or indexed color which is not correctly converted to RGBA format.

thanks,
