### ISSUE TITLE
EXC_BAD_ACCESS at getColorCode

### ISSUE THREAD

**Issue by dmaulikr** [Chintan-Dave/UIImageScanlineFloodfill#35]
In method (from UIImage+FloodFill.m)

In iPhone its working like charm but when I tried it on iPad its giving error EXC_BAD_ACCCESS exception in getColorCode method.

I'm getting error on "unsigned int red   = imageData[byteIndex]" line.

Suggestion in #23 not worked at all.

**Comment by goharika** [comment]
Hi,
I am getting issue too when filling with color. On the same row.
And it returns thread issue, how have you fixed this problem for you?
