### ISSUE TITLE
Get the numberOfPortions to fill in the image

### ISSUE THREAD

**Issue by MuraliV1983** [Chintan-Dave/UIImageScanlineFloodfill#37]
The code is really very helpful, but i need to get the frames count to be coloured. (ie) the count of the colouring portions in the image, how to get this ?

Thanks,

**Comment by Chintan-Dave** [comment]
@MuraliV1983  can you explain more in detail what you need? Have you any sample output?

**Comment by Chintan-Dave** [comment]
I am closing this issue due to an unclear idea and long time inactivity.
